name: gacha-tdd-pipeline

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - run: pip install -r requirements.txt

      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - run: pytest test_business_logic.py -v